name: Publish to WinGet

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: '対象のタグ名'
        required: true
        default: 'v'

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Neosku.AviUtl2-Catalog
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
          release-tag: ${{ inputs.tag_name || github.event.release.tag_name }}
